apiVersion: lexicore.io/v1
kind: SyncTarget
metadata:
  name: mail-provisioning
spec:
  sourceRef: authentik
  operator: iredadmin
  dryRun: true
  config:
    url: "https://test.test.com/iredadmin"
    username: "test@test.com"
    password: ""
  transformers:
    - name: mail-settings
      type: template
      config:
        templates:
          iredadmin:cn: "{{ .DisplayName }}"
          iredadmin:givenName: "{{ .Attributes.givenName }}"
          iredadmin:sn: "{{ .Attributes.sn }}"
