apiVersion: lexicore.io/v1
kind: SyncTarget
metadata:
  name: mail-provisioning
spec:
  sourceRef: authentik
  operator: iredadmin
  dryRun: true
  config:
    deleteOnDelete: false
    deleteOnDisable: false
    keepMailboxDays: 30
    domain: test.com
    attributePrefix: "iredadmin:"
    url: "https://test.test.com/iredadmin"
    username: "test@test.com"
    password: ""
  transformers:
    - name: mail-settings
      type: template
      config:
        templates:
          iredadmin:cn: "{{ .DisplayName }}"
          iredadmin:givenName: "{{ .Attributes.givenName }}"
          iredadmin:sn: "{{ .Attributes.sn }}"
    - name: aggregate-group-attrs
      type: groupAggregation
      config:
        mappings:
          # Mail quota: use the highest quota from all groups
          - sourceAttribute: mailQuota
            targetAttribute: iredadmin:mailQuota
            aggregationMode: max
            defaultValue: 1073741824 # 1GB default

          # Language: use the first group's language
          - sourceAttribute: defaultLanguage
            targetAttribute: iredadmin:preferredLanguage
            aggregationMode: first
            defaultValue: en_US

          # Mail domain: use last group's domain (priority groups)
          - sourceAttribute: mailDomain
            targetAttribute: iredadmin:mailDomain
            aggregationMode: last

          # Enabled services: aggregate from all groups
          - sourceAttribute: enabledServices
            targetAttribute: iredadmin:enabledService
            aggregationMode: append

          # Title: use minimum (for hierarchical titles)
          - sourceAttribute: title
            targetAttribute: iredadmin:title
            aggregationMode: min
