apiVersion: lexicore.io/v1
kind: SyncTarget
metadata:
  name: dovecot-provisioning
spec:
  sourceRef: corporate-ldap
  operator: dovecot-acl
  config:
    url: "http://dovecot-server:8080/doveadm/v1"
    api_key: "${DOVECOT_API_KEY}"
  transformers:
    - name: dovecot-metadata
      type: template
      config:
        templates:
          # This maps to the 'right' parameter in 'acl set'
          # Syntax: "identifier right" (e.g., "user=admin lr")
          dovecot_acl: "user=admin lrs"
