apiVersion: lexicore.io/v1
kind: SyncTarget
metadata:
  name: sogo-granular-calendar-acls
spec:
  sourceRef: authentik-prod
  operator: caldav-acl
  config:
    url: "https://sogo.example.com/SOGo"
    username: "davadmin@example.com"
    password: "${SOGO_ADMIN_PASS}"
  syncPeriod: 5m
  transformers:
    - name: filter-valid-users
      type: selector
      config:
        attributeSelector:
          field: email
          operator: notEmpty
    - name: compute-acl-privileges
      type: template
      config:
        templates:
          caldav_folder: "Calendar/personal"
          caldav_acl: >-
            {{- if in "managers" .Groups -}}
              authenticated:read,bind,write-content,unbind
            {{- else -}}
              authenticated:read,bind,write-content
            {{- end -}}
    - name: normalize-email
      type: sanitizer
      config:
        sanitizers:
          - field: email
            type: lowercase
